// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPiq2EUpsZtKnVDwk4k5w0TaveV6kt2N0',
    appId: '1:323904209591:web:2905a03a7bac87ef730332',
    messagingSenderId: '323904209591',
    projectId: 'smart-handagote',
    authDomain: 'smart-handagote.firebaseapp.com',
    storageBucket: 'smart-handagote.appspot.com',
    measurementId: 'G-THEB9HY42J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnIbGKbWFtJtdFnsBTHhWFKZIL5D9nIdk',
    appId: '1:323904209591:android:f3652e2fbe992993730332',
    messagingSenderId: '323904209591',
    projectId: 'smart-handagote',
    storageBucket: 'smart-handagote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLSY5rcSw4w_yddGqDSYAuMp1Ht5cmwEs',
    appId: '1:323904209591:ios:c841242c4e7cfbc7730332',
    messagingSenderId: '323904209591',
    projectId: 'smart-handagote',
    storageBucket: 'smart-handagote.appspot.com',
    iosClientId: '323904209591-e7dhms06dee279g554cem67cm7bl4j84.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHandagote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLSY5rcSw4w_yddGqDSYAuMp1Ht5cmwEs',
    appId: '1:323904209591:ios:5716343d0e016d92730332',
    messagingSenderId: '323904209591',
    projectId: 'smart-handagote',
    storageBucket: 'smart-handagote.appspot.com',
    iosClientId: '323904209591-c4cm2l3bibbokdkjpnl8l5ii2ana39qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHandagote.RunnerTests',
  );
}
